version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitMQ
    hostname: ${RABBITMQ_DATABASE_NAME}
    restart: on-failure
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MNGT_PORT}:15672"
    volumes:
      - ../rabbitmq/prod/:/etc/rabbitmq/
    networks:
      - backend
  
  redis:
    image: redis:4-alpine
    container_name: "boilerplate-redis-production"
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../logs/redis/:/usr/local/etc/redis/logs/
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - backend

  mongodb:
    image: mongo:4
    container_name: mongoDb
    restart: on-failure
    volumes:
      - ../mongodb/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_APP_USER=${MONGO_DB_USER}
      - MONGO_APP_PW=${MONGO_DB_PW}
      - MONGO_APP_USER_AUTH_METHOD=${MONGO_DB_AUTH_METHOD}

  configloader:
    init: true
    container_name: "boilerplate-configLoader-production"
    restart: on-failure
    image: "TBD"
    build:
      context: ../
      dockerfile: ./docker/configLoader/Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
      - rabbitmq
      - cache
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DEPLOY_STAGE=production
      - SLEEP_MS=${CONFIGLOADER_SLEEP_MS}
      - QUEUE_CON_URL=amqp://${RABBITMQ_APP_USER}:${RABBITMQ_APP_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

  mailer:
    init: true
    container_name: "boilerplate-mailer-production"
    restart: on-failure
    image: "TBD"
    build:
      context: ../
      dockerfile: ./docker/mailer/Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
      - rabbitmq
    ports:
      - "${MAILER_SOCKET_SERVER_PORT}:${MAILER_SOCKET_SERVER_PORT}"
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DEPLOY_STAGE=production
      - SOCKET_SERVER_PORT=${MAILER_SOCKET_SERVER_PORT}
      - QUEUE_CON_URL=amqp://${RABBITMQ_APP_USER}:${RABBITMQ_APP_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - MAIL_HOST=${MAILHOG_HOST}
      - MAIL_PORT=${MAILHOG_EMAIL_PORT}

  cache:
    init: true
    container_name: "boilerplate-cache-production"
    restart: on-failure
    image: "TBD"
    build:
      context: ../
      dockerfile: ./docker/cache/Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "${CACHE_SOCKET_SERVER_PORT}:${CACHE_SOCKET_SERVER_PORT}"
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DEPLOY_STAGE=production
      - SOCKET_SERVER_PORT=${CACHE_SOCKET_SERVER_PORT}
      - QUEUE_CON_URL=amqp://${RABBITMQ_APP_USER}:${RABBITMQ_APP_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  
  db:
    init: true
    container_name: "boilerplate-db-production"
    restart: on-failure
    image: "TBD"
    build:
      context: ../
      dockerfile: ./docker/db/Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "${DB_SOCKET_SERVER_PORT}:${DB_SOCKET_SERVER_PORT}"
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DEPLOY_STAGE=production
      - SOCKET_SERVER_PORT=${DB_SOCKET_SERVER_PORT}
      - QUEUE_CON_URL=amqp://${RABBITMQ_APP_USER}:${RABBITMQ_APP_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - DB_CONNECT_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PW}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authMechanism=${MONGO_DB_AUTH_METHOD}
      - DB_MIGRATION_CONNECT_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin?authMechanism=${MONGO_DB_AUTH_METHOD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

  webServer:
    init: true
    container_name: "boilerplate-webServer-production"
    restart: on-failure
    image: "TBD"
    build:
      context: ../
      dockerfile: ./docker/webServer/Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
      - rabbitmq
      - cache
      - configloader
      - mailer
    ports:
      - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
    volumes:
      - ./logs/webServer/:/src/webServer/logs/
      - ./frontend/:/src/webServer/frontend/
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DEPLOY_STAGE=production
      - PORT=${WEBSERVER_PORT}
      - QUEUE_CON_URL=amqp://${RABBITMQ_APP_USER}:${RABBITMQ_APP_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - CACHE_HOST=${CACHE_SOCKET_SERVER_HOST}
      - CACHE_PORT=${CACHE_SOCKET_SERVER_PORT}
      - MAILER_HOST=${MAILER_SOCKET_SERVER_HOST}
      - MAILER_PORT=${MAILER_SOCKET_SERVER_PORT}
      - DB_HOST=${DB_SOCKET_SERVER_HOST}
      - DB_PORT=${DB_SOCKET_SERVER_PORT}

networks:
  backend: